---
- name: Set Ip Loobpack
  hosts: all
  gather_facts: no
tasks:
	- name: Set loopback IPv4 address
		ios_l3_interface:
			name: loopback {{items.No}}
			ipv4: {{items.IP}}/24
		with_items:
			- {No: 1, IP: 10.10.10.1}
			- {No: 2, IP: 10.10.20.1}
			- {No: 3, IP: 10.10.30.1}
	- name: Show interface
		ios_command:
			- show ip int br
		register: show_interface
	- debug: var = show_interface.stdout_lines
